"""empty message

Revision ID: 44e6bea9b0b0
Revises: 7d06427c8cb6
Create Date: 2018-07-17 00:24:28.111396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e6bea9b0b0'
down_revision = '7d06427c8cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange', 'from_currency',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('exchange', 'to_currency',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange', 'to_currency',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('exchange', 'from_currency',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###
