"""empty message

Revision ID: 7d06427c8cb6
Revises: 
Create Date: 2018-07-12 03:13:01.556674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d06427c8cb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=12), nullable=True),
    sa.Column('to_currency', sa.String(length=12), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_from_currency'), 'exchange', ['from_currency'], unique=False)
    op.create_index(op.f('ix_exchange_to_currency'), 'exchange', ['to_currency'], unique=False)
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rate')
    op.drop_index(op.f('ix_exchange_to_currency'), table_name='exchange')
    op.drop_index(op.f('ix_exchange_from_currency'), table_name='exchange')
    op.drop_table('exchange')
    # ### end Alembic commands ###
